# Generated by Django 5.2.8 on 2025-12-03 05:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='post',
            name='data_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
